tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "coreutils"
brew "libyaml"
brew "asdf"
brew "awscli"
brew "bash"
brew "bat"
brew "curl"
brew "diff-so-fancy"
brew "fd"
brew "git"
brew "jq"
brew "lcov"
# brew "lazydocker"
brew "lazygit"
brew "lua-language-server"
brew "neovim"
# brew "postgresql"
# brew "mysql", restart_service: true
# brew "redis", restart_service: true
brew "ripgrep"
brew "tree"
brew "tidy-viewer"
brew "wget"
brew "zsh"
brew "shared-mime-info"
cask "aerial"
cask "alfred"
cask "firefox"
cask "google-chrome"
cask "iina"
cask "shottr"
cask "slack"
cask "tableplus"
cask "the-unarchiver"
cask "visual-studio-code"
cask "1password"
cask "orbstack"
cask "warp"
