-- local lines = {'one', 'two', 'three'}
-- local buf = vim.api.nvim_create_buf(false, true)
-- vim.api.nvim_buf_set_lines(buf, 0, -1, true, {'hello'})
-- vim.api.nvim_open_win(buf, true, {
--       relative = "editor",
--       style = "minimal",
--       width = 30,
--       height = 3,
--       row = 0,
--       col = 0,
--       border = "double"
--     })
